### ISSUE TITLE
Implement plugin system

### ISSUE THREAD

**Issue by tobiase** [tobiase/worktree-utils#6]
## Overview
Allow extending wt with plugins from external repositories.

**Priority**: Low - This is a nice-to-have feature but not essential for core functionality.

### Plugin structure
```
my-wt-plugin/
├── plugin.yaml     # Metadata
├── main.go        # Plugin code
└── README.md
```

### plugin.yaml
```yaml
name: deploy
version: 1.0.0
description: Deploy worktree to staging
commands:
  - name: deploy
    description: Deploy current worktree
```

### Commands
- `wt plugin add github.com/user/wt-deploy`
- `wt plugin list`
- `wt plugin remove deploy`
- `wt plugin create my-plugin`

## Implementation considerations
- [ ] Plugin discovery and loading
- [ ] Version management
- [ ] Security (signing?)
- [ ] Plugin isolation
- [ ] Configuration merging

## MVP scope
- Simple executable plugins
- JSON/stdout communication
- Manual installation
